### ISSUE TITLE
No error: PDO constructor was not called

### ISSUE THREAD

**Issue by ThomasDelap** [andreossido/laravel-odbc#3]
Hi,

The error :

`   ⚠: ThrowingCasterException {#262 ▼
        #message: "Unexpected ErrorException thrown from a caster: PDO::getAttribute(): SQLSTATE[00000]: No error: PDO constructor was not called"
        trace: {▼
          C:\laragon\www\ppe3\vendor\symfony\var-dumper\Caster\PdoCaster.php:63 {▶}
          C:\laragon\www\ppe3\vendor\symfony\var-dumper\Cloner\AbstractCloner.php:231 {▶}
          Symfony\Component\VarDumper\Cloner\AbstractCloner->Symfony\Component\VarDumper\Cloner\{closure}() {}
          C:\laragon\www\ppe3\vendor\symfony\var-dumper\Caster\PdoCaster.php:63 {▶}
        }
      }
      #connection: odbc link resource @233`

**Comment by andreossido** [comment]
Can you give more informations? (ex: your config files)
