### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by CraigBSM** [andreossido/laravel-odbc#5]
Hey, chances of this project getting updated to work with Laravel 6?

and maybe with package auto discovery? https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

**Comment by andreossido** [comment]
I didn't know package auto discovery. 
Yes, I can try to implement it. (or I accept PR if you want to develop it)
Also I can try do update it for Laravel 6

**Comment by andreossido** [comment]
I found a fork of my project. It works with Laravel 6+
https://github.com/DavidRodarte/laravel-odbc
